In [23]:
import numpy as np

1- Given are 2 similar dimensional numpy arrays, how to get a numpy array output
in which every element is an element-wise sum of the 2 numpy arrays?

In [4]:
n1=np.array(([10,12,13],[11,14,15]))
n2=np.array(([10,11,12],[14,15,11]))
n3=np.add(n1,n2)
n3

array([[20, 23, 25],
       [25, 29, 26]])

2- Given a numpy array (matrix), how to get a numpy array output which is equal to
the original matrix multiplied by a scalar?

In [43]:
a1=np.array(([10,12,13],[11,14,15]))
print(a1)
n4=a1*10
n4

[[10 12 13]
 [11 14 15]]


array([[100, 120, 130],
       [110, 140, 150]])

3- Create an identity matrix of dimension 4-by-4

In [24]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4- Convert a 1-D array to a 3-D array

In [18]:
a_1d=np.array([1,2,3,4,5,6])
a_1d.ndim


1

In [19]:
a_3d=np.reshape(a_1d,(1,2,3))


array([[[1, 2, 3],
        [4, 5, 6]]])

In [36]:
a_3d.ndim

3

5- Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

In [40]:
S1=np.eye(3,3)
print(S1)
S1.astype(bool)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

6- Convert all the elements of a numpy array from float to integer datatype


In [41]:
f=np.array([[2.23,5.53],[5.5,6.2]])
print(f)
f.astype(int)


[[2.23 5.53]
 [5.5  6.2 ]]


array([[2, 5],
       [5, 6]])

8- Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both
inclusive)

In [42]:
t=np.arange(0,101,25)
t

array([  0,  25,  50,  75, 100])

12- Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [38]:
x1=np.random.rand(5,3)
x1

array([[0.6822284 , 0.99064124, 0.89652778],
       [0.22362298, 0.32847781, 0.44419147],
       [0.735811  , 0.4173623 , 0.19916957],
       [0.74390166, 0.01630121, 0.61634627],
       [0.56624505, 0.26700516, 0.74467394]])

In [31]:
x2=np.random.rand(3,2)
x2

array([[0.96942689, 0.40506794],
       [0.98784503, 0.69449103],
       [0.59368114, 0.7835991 ]])

In [33]:
x3=np.dot(x1,x2)
x3

array([[1.50648908, 1.01449879],
       [0.96817004, 0.90830781],
       [1.27645493, 1.01407625],
       [0.95033562, 0.66121641],
       [1.16428532, 0.98977596]])